import { FileDown, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import type { Employee } from "@/data/mockData";

function generateMarkdown(emp: Employee, managerNotes: string): string {
  return `# Performance Review — ${emp.name}

**Role:** ${emp.role} · ${emp.team}
**Review Period:** Q4 2025
**Date:** ${new Date().toLocaleDateString()}

---

## Performance Summary

${emp.aiSummary}

## Key Accomplishments

${emp.keyAccomplishments.map((a) => `- ${a}`).join("\n")}

## Highlights

${emp.highlights.map((h) => `- ${h}`).join("\n")}

## Areas for Growth

${emp.areasForGrowth.map((a) => `- ${a}`).join("\n")}

## Metrics

| Metric | Value |
|--------|-------|
| Goal Completion | ${emp.goalCompletion}% |
| Projects Completed | ${emp.projectsCompleted} |
| 1:1 Sessions | ${emp.oneOnOneCount} |
| Peer Feedback Score | ${emp.peerFeedbackScore}/5 |

## Manager Notes

${managerNotes || "No additional notes."}

---

*Generated by ReviewPrep · AI-Powered Performance Review Assistant*
`;
}

interface ExportButtonsProps {
  employee: Employee;
  managerNotes: string;
}

export function ExportButtons({ employee, managerNotes }: ExportButtonsProps) {
  const handleCopy = async () => {
    const md = generateMarkdown(employee, managerNotes);
    await navigator.clipboard.writeText(md);
    toast.success("Review copied to clipboard as markdown");
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" onClick={handlePrint} className="border-border text-foreground hover:bg-secondary">
        <FileDown size={14} className="mr-1.5" /> Export PDF
      </Button>
      <Button variant="outline" size="sm" onClick={handleCopy} className="border-border text-foreground hover:bg-secondary">
        <Copy size={14} className="mr-1.5" /> Copy
      </Button>
    </div>
  );
}
